name: Test action

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Print all environment variables"
      - run: env
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Send mail
        uses: ./
        with:
          server_address: ${{secrets.SMTP_SERVER}}
          server_port: 465
          username: ${{secrets.SMTP_USER}}
          password: ${{secrets.SMTP_PASS}}
          subject: hallihallo
          body: nix
          headers: | 
             {"Approved":"${{secrets.ML_APPROVED}}","X-Approved":"Bar",
             "X-Foo":"Bar"}
          to: ${{secrets.ML_ADDRESS}}
          from: github-actions
          attachments: ${{matrix.attachments}}
          convert_markdown: ${{matrix.convert_markdown}}
          priority: high
